name: mbtifrontend
description: "A new mbti project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  # 백엔드로 DB 요청 보내기 위한 패키지 GET POST PUT DELETE
  # dio 사용할 것
#  http: ^1.1.0
  dio: ^5.4.0
  # 상태 관리 패키지 데이터를 공유하고 관리할 수 있다.
  # 추후 riverpod 사용할 것이다.
  provider: ^6.1.1
  # 날짜/숫자 포멧 다국어
  # easy_localization 다국어 지원 시 사용할 것
  intl: ^0.18.1
  # navigation의 향상된 버전
  # 경로 이동에 사용된다.
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  # 로그인 상태 저장 모듈
  shared_preferences: ^2.2.2
  # 카카오맵 플러그인 JS Key를 가져와서 위젯으로 포장하고 기능을 활용할 것이다.
  # 안드로이드나 IOS 네이티브 언어는 전용 Key를 가져와야 한다.
  kakao_map_plugin: ^0.3.7
  # 내 위치(GPS) 좌표를 가져오는 도구이다.
  # 지도 기능 사용 시 필수로 함께 사용해야 한다.
  # 안드로이드와 IOS의 위치(좌표)는 동일한 방식으로 사용하는가? 위치 관련 권한은 추가해야 하는가?
  geolocator: ^13.0.1
  # 토스 결제
  tosspayments_webview_flutter: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

